// Generated by CoffeeScript 1.6.3
(function() {
  var nuimotion;

  nuimotion = require("nuimotion");

  this.Joints = nuimotion.Joints;

  this.boilerplate = function() {
    var Events, swipe, wave;
    Events = nuimotion.Events;
    swipe = Events.Gestures.Swipe.types;
    wave = Events.Gestures.Wave.types;
    nuimotion.startSkeletonListener([Joints.LEFT_HAND, Joints.RIGHT_HAND], this.onSkeletonUpdate, 33);
    nuimotion.addListener([Events.SKELETON_TRACKING, Events.SKELETON_STOPPED_TRACKING], this.onUserEvent);
    nuimotion.addGesture([swipe.up, swipe.down, swipe.left, swipe.right, wave.hand], this.onGesture);
    nuimotion.init();
    process.on("exit", function() {
      return nuimotion.close();
    });
  };

}).call(this);
