// Generated by CoffeeScript 1.6.3
(function() {
  var terminal;

  global.x = 0;

  global.y = 0;

  global.click = false;

  global.childProcess = require('child_process');

  terminal = global.childProcess.spawn('bash');

  terminal.stdout.on('data', function(data) {
    return console.log('stdout: ' + data);
  });

  terminal.on('exit', function(code) {
    return console.log('child process exited with code ' + code);
  });

  setInterval(function() {
    var command;
    console.log('Sending stdin to terminal');
    command = '';
    if (global.click) {
      command = 'touch /home/emiliano/Scaricati/mongoose/build/on';
    }
    terminal.stdin.write(command);
    terminal.stdin.end();
    return terminal = global.childProcess.spawn('bash');
  }, 1000);

  this.onSkeletonUpdate = function(data) {
    var xLeft, yLeft, yRight;
    $("#rightHand").css("font-size", "100px");
    xLeft = data.skeleton[Joints.LEFT_HAND].x;
    yLeft = data.skeleton[Joints.LEFT_HAND].y;
    yRight = data.skeleton[Joints.RIGHT_HAND].y;
    $("#rightHand").text(yRight);
    global.x = Math.min(Math.max(0, (-xLeft + 500) * 2), 1980);
    global.y = Math.min(Math.max(0, -yLeft + 500), 1020);
    global.click = yRight < 200 && yRight > 0;
  };

  boilerplate.call(this);

}).call(this);
